image: node:latest

stages:
  - production

production:
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - echo $HEROKU_API_KEY
    - dpl --provider=heroku --app=colin-harfst-site --api-key=$HEROKU_API_KEY
  only:
    - master
